### ISSUE TITLE
Multiple RateLimiter

### ISSUE THREAD

**Issue by elreco** [spatie/guzzle-rate-limiter-middleware#10]
Hello,

thank you for the package,

can we have multiple Rate Limiter like below?

```php
$stack = HandlerStack::create();
$stack->push(RateLimiterMiddleware::perSecond(20));
$stack->push(RateLimiterMiddleware::perMinute(100));
```

thank you

**Comment by dmyers** [comment]
Have you tried this out? I think it would work since you can push multiple middleware to Guzzle stack handlers as long as your deferrer is sleep based and they try to get atomic locks then it should just compound the time waited sleeping.

**Comment by dmyers** [comment]
Sorry I'm tired I misread the issue. I think this would definitely require a custom rate limiter middleware or at least a store or deferrer that takes into account how many requests that have occurred each timeframe which might mean a different rate limiting class altogether since the current one just passes timestamps.

**Comment by sebastiandedeyne** [comment]
Do you have an example use case for this?

**Comment by sebastiandedeyne** [comment]
Wouldn't sharing a single store instance be enough?
